osx_image: xcode9.2
language: objective-c
xcode_workspace: LinkedIdeas.xcworkspace
sudo: false
git:
  submodules: false
cache:
  - bundler
  - cocoapods
script:
  - fastlane ios test
  - fastlane mac test
  - swiftlint
