osx_image: xcode9.4
language: objective-c
xcode_workspace: LinkedIdeas.xcworkspace
sudo: false
git:
  submodules: false
cache:
  - bundler
  - cocoapods
install:
  - bundle install
script:
  - bundle exec fastlane ios test
  - bundle exec fastlane mac test
